apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idurar-frontend.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJra3A3ODUyMTYiLCJwYXNzd29yZCI6Iks4ODU4ODk5OTU4QCIsImVtYWlsIjoia2twNzg1MjE2QGdtYWlsLmNvbSIsImF1dGgiOiJhMnR3TnpnMU1qRTJPa3M0T0RVNE9EazVPVFU0UUE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
